name: run

on:
  push:
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt

      - name: Run RFE demo
        run: |
          python src/rfe_simple.py --min_features 5
          test -f results/rfe_features.csv
          test -f results/rfe_nfeat_vs_auc.png
          test -f results/metrics_rfe.json
          test -f results/rfe_coeffs_top12.png || true
          test -f results/svm_coefficients.csv || true

      - name: Run Nested + Stability (RFE)
        run: |
          python src/rfe_nested_stability.py --min_features 5 --n_outer 5 --n_repeats 50 --subsample 0.8
          test -f results/metrics.csv
          test -f results/summary.json
          test -f results/features_selected.csv
          test -f results/stability_top20.png

      - name: Run Sparse Group Lasso (SGL)
        run: |
          python src/sgl_stability.py --n_repeats 50 --subsample 0.8
          test -f results/sgl_summary.json
          test -f results/sgl_grid_auc.png
          test -f results/sgl_stability_top20.png

      - name: Upload artifacts (results)
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/
